version: '3.9'

services:
  plannerapp:
    container_name: plannerapp
    image: kindercentrum/plannerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://plannerdb:5432/postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - plannerdb

  plannerdb:
    container_name: plannerdb
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

